nesso:
  target: "{{ env_var('NESSO_DBT_TARGET') }}"
  outputs:
    dev:
      type: "{{ env_var('NESSO_DBT_DB_TYPE') }}"
      host: "{{ env_var('NESSO_DBT_DB_HOST') }}"
      port: "{{ env_var('NESSO_DBT_DB_PORT') | int }}"
      dbname: "{{ env_var('NESSO_DBT_DB_NAME') }}"
      schema: "{{ env_var('NESSO_DBT_DB_SCHEMA') }}"
      user: "{{ env_var('NESSO_DBT_DB_USER') }}"
      password: "{{ env_var('DBT_ENV_SECRET_NESSO_DB_PASSWORD') }}"
      threads: "{{ env_var('NESSO_DBT_THREADS') | int }}"
      retries: "{{ env_var('NESSO_DBT_RETRIES') | int }}"
